### ISSUE TITLE
Unexpected ASCII output

### ISSUE THREAD

**Issue by mscdex** [a2800276/hexy.js#17]
Node's built-in ASCII Buffer encoding basically just does `& 0x7F` for every byte, which leads to unexpected ASCII characters showing up for bytes > 0x7F.

I think it would be better to at least have an option to show a dot for such byte values. Not only does this make more sense to some of us, but the resulting output would also align with other tools with split output (e.g. wireshark).

**Comment by a2800276** [comment]
@mscdex  thanks for the input. Sound reasonable and I should be able to quickly build a patch. Could you provide a sample of text that provides unexpected results and how you would have expected the formatting?

**Comment by mscdex** [comment]
Here's an example:

```js
const buf = Buffer.from('68656c6c6fd2776f726c64', 'hex');
console.log(require('hexy').hexy(buf));
```

Current resulting output:

```
00000000: 6865 6c6c 6fd2 776f 726c 64              helloRworld
```

Better resulting output with non-ASCII bytes "ignored":

```
00000000: 6865 6c6c 6fd2 776f 726c 64              hello.world
```

**Comment by a2800276** [comment]
Thanks, agree, I'll try to make a fix asap. Input is greatly appreciated!

**Comment by a2800276** [comment]
I think [this](https://github.com/a2800276/hexy.js/pull/18) should take care of it, but I'd like to mull over it for a night, because javascript byte handling and character encoding are tricky.

Basically, I thought I handled this case by using a regex to replace all non printable bytes (i.e. `raw.replace(/[\000-\040\177-\377]/g, ".")`)  but it seems that regexps are multibyte/unicode aware (a bit handwavy, at least the regexp above doesn't replace the `d2` in your example above)

For now I'm using the regexp to purge spaces and traditional non-printable ascii and furthermore iterating over the input and eliminating everything >= 127 manually. Not sure if I can rely on all multichar bytes to be >=127, though. So I might have to do some light reading later tonight. Of course if you're knowledgeable and can answer spontaneously, I'd appreciate feedback :)

(Oh and ignore that the CI tests are failing for now, I got used to `let` and `const` declarations, but I'm also testing with ancient node versions and I haven't decided yet which I should prioritize ...)

**Comment by mscdex** [comment]
> Basically, I thought I handled this case by using a regex to replace all non printable bytes (i.e. `raw.replace(/[\000-\040\177-\377]/g, ".")`) but it seems that regexps are multibyte/unicode aware (a bit handwavy, at least the regexp above doesn't replace the `d2` in your example above)

That `replace()` happens _after_ the `toString('ascii')`, so it will never have a chance to match non-ASCII bytes.

Probably the easiest solution is if the special option is set, use `'latin1'` instead of `'ascii'` when converting the Buffer to a string. That will give you a JavaScript string, but will keep individual bytes intact and will cause your regexps to match the non-ASCII bytes as you are expecting.

On an unrelated note, I appreciate the mention in the commit message you linked to but I'd prefer to have my name removed. It sends a bunch of notifications (including any/every time someone pushes the same commit to their fork for example).

**Comment by a2800276** [comment]
... mention in the commit message ...

done. I'll have a look at the latin1 suggestion when I'm a bit less busy. And will also try to understand with the 'ascii' conversion does 0xD2 -> 'R' ...

**Comment by mscdex** [comment]
> And will also try to understand with the 'ascii' conversion does 0xD2 -> 'R' ...

It's simple: when you call `.toString('ascii')` node simply truncates the higher bit on each byte in the Buffer. It'd be equivalent to:

```js
function convertToASCII(buf) {
  const asciiBuf = Buffer.from(buf);

  for (let i = 0; i < result.length; ++i)
    asciiBuf[i] &= 0x7F; // only keeps the lower 7 bits

  return asciiBuf.toString();
}

const result = convertToASCII(Buffer.from('68656c6c6fd2776f726c64', 'hex'));
// result === 'helloRworld'
```

In this particular case: `0xD2 & 0x7F` becomes `0x52`, which is the ASCII value for `'R'`.

**Comment by a2800276** [comment]
￼
D'oh, obviously. Thanks for pointing it out.

**Comment by rom-p** [comment]
Actually, the way to deal with it is to call `.toString('binary')`.  I implemented this in the fork I just created: https://github.com/rom-p/hexy.js.  It has a few other features implemented (parameters for endianness, radix for binary data, 8-byte chunks, etc.).  I added the case discussed in this thread to the tests in that change

LMK if you'd like me to submit a pull request

**Comment by mscdex** [comment]
> Actually, the way to deal with it is to call `.toString('binary')`

`'latin1'` is the modern/preferred alias for `'binary'`.

**Comment by rom-p** [comment]
thank you for pointing it out.  To me, `'binary'` semantically sounds like "do not do any transformations" whereas `'latin1'` is one of the actual encodings, even though they are exactly the same.

In any case, updated that in my branch, if you're interested.

**Comment by a2800276** [comment]
closed by https://github.com/a2800276/hexy.js/pull/19
