### ISSUE TITLE
BigInt issue with @vercel/ncc

### ISSUE THREAD

**Issue by erossignon** [a2800276/hexy.js#20]
Trying to package hexy with @vercel/ncc causes this error

```
// test.js
require("hexy");
```` 

````
$npx -y @vercel/ncc build test.js
````

ncc produces this error
````
[....]
typeError: Cannot mix BigInt and other types, use explicit conversions
[....]
`````

Testing with @0.3.3

I suspect we are combining BigInt and number in some expression.

**Comment by erossignon** [comment]
Yes, strictly speaking, the original code was fine to me as well.
I believe that NCC is using some sort of javascript code parser and manipulation of the AST during the minifying process. 
The minifier get tricked by the the line : var  x = condition ? BigInt(0) : 0; I guess because the type of X is not determined at initialization.
We will have to asked the ncc team to get more detailed info

**Comment by rom-p** [comment]
I'm the author of the faulting line.  Sorry for the trouble this has caused.

I think the proposed **fix is correct.**  I tested it on several platforms I have access to: x64 Windows 10 with node.js v14.16.0,  x64 Linux 5.4.0 with node.js v10.19.0,  aarch64 Linux 5.10 with node.js v10.24.0,  and aarch64 macOS with node v17.0.1 -- all passing with the proposed fix.

Why I think the fix is correct: according to both https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt and https://262.ecma-international.org/12.0/, chapter 6.1.6:

> Because the numeric types are in general not convertible without loss of precision or truncation, the ECMAScript language provides no implicit conversion among these types. Programmers must explicitly call Number and BigInt functions to convert among types when calling a function which requires another type.

(and the note right after, which I think describes the scenario we're experiencing)

How the bug came to be: having little experience with JavaScript, I mentally applied the implicit conversion rules from C/C++, where conversion to a bigger and/or more precise type is done automatically.  Turns out, this worked for some versions of JavaScript, but it's not in the standard.

**Comment by a2800276** [comment]
ok, seems innocuous enough. I'll go ahead and merge bump, release.

**Comment by a2800276** [comment]
Ok, everything should be up to date, and 0.3.4 available via npm.

(Everything except the Thanks section of the README, which I've been somewhat lazy about, so thanks very much @erossignon  and especially @rom-p  for your previous patches!)
